### ISSUE TITLE
question

### ISSUE THREAD

**Issue by FFFFFancy** [AnXingju/Program-on-Python#1]
Trying to run your project but encountered some problems 
Could you please give me your email to contact you?
thank u

**Comment by AnXingju** [comment]
You may need to install the Django framework.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AnXingju/Program-on-Python"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月23日(星期二) 中午11:41
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[AnXingju/Program-on-Python] question (Issue #1)





 
Trying to run your project but encountered some problems
 Could you please give me your email to contact you?
 thank u
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by FFFFFancy** [comment]
sorry，前面没有解释清楚。
我运行的project是您的imdb sentiment analysis，我在kaggle和jupyter notebook平台上都尝试了，前面没有遇到问题，但是到了training的部分一直没有得到正确的训练结果，我大概都尝试运行了三个小时以上，但是后面几部分没有得到任何输出（plt的图也是空的，没有数据），请问应该有的正确输出是什么样子的呢？




发自我的iPhone


------------------ Original ------------------
From: AnXingju ***@***.***&gt;
Date: Tue,Nov 23,2021 0:21 PM
To: AnXingju/Program-on-Python ***@***.***&gt;
Cc: FFFFFancy ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [AnXingju/Program-on-Python] question (Issue #1)





 You may need to install the Django framework. 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "AnXingju/Program-on-Python"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年11月23日(星期二) 中午11:41 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;; 
 主题:&amp;nbsp;[AnXingju/Program-on-Python] question (Issue #1) 
 
 
 
 
 
   
 Trying to run your project but encountered some problems 
  Could you please give me your email to contact you? 
  thank u 
   
 — 
 You are receiving this because you are subscribed to this thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AnXingju** [comment]
里面两处代码你可能需要自己调整一下哦，acc()方法里的参数都转换成float类型，batch_size设置成16。训练后的结果是这个图咯。后续的查找关键字报错和代码没关系，您需要自己找合适的数据集哦~


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AnXingju/Program-on-Python"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月24日(星期三) 晚上7:32
***@***.***&gt;;
抄送:&nbsp;"时光 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [AnXingju/Program-on-Python] question (Issue #1)





 sorry，前面没有解释清楚。 
 我运行的project是您的imdb sentiment analysis，我在kaggle和jupyter notebook平台上都尝试了，前面没有遇到问题，但是到了training的部分一直没有得到正确的训练结果，我大概都尝试运行了三个小时以上，但是后面几部分没有得到任何输出（plt的图也是空的，没有数据），请问应该有的正确输出是什么样子的呢？ 
 
 
 
 
 发自我的iPhone 
 
 
 ------------------ Original ------------------ 
 From: AnXingju ***@***.***&amp;gt; 
 Date: Tue,Nov 23,2021 0:21 PM 
 To: AnXingju/Program-on-Python ***@***.***&amp;gt; 
 Cc: FFFFFancy ***@***.***&amp;gt;, Author ***@***.***&amp;gt; 
 Subject: Re: [AnXingju/Program-on-Python] question (Issue #1) 
 
 
 
 
 
  You may need to install the Django framework.  
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "AnXingju/Program-on-Python"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年11月23日(星期二) 中午11:41  
  ***@***.***&amp;amp;gt;;  
  ***@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;[AnXingju/Program-on-Python] question (Issue #1)  
   
   
   
   
   
     
  Trying to run your project but encountered some problems  
   Could you please give me your email to contact you?  
   thank u  
     
  —  
  You are receiving this because you are subscribed to this thread.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.  
 — 
 You are receiving this because you authored the thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
